apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: path-based-ingress
  annotations:
    nginx.ingress.kubernetes.io/default-backend: ingress-nginx-controller-admission 
    nginx.ingress.kubernetes.io/rewrite-target: /$5
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  rules:
    - host: {{FQDN}}
      http:
        paths:
        - path: /choose
          backend:
              serviceName: update
              servicePort: 80
        - path: /update
          backend:
              serviceName: update
              servicePort: 80
        - path: /delete
          backend:
              serviceName: update
              servicePort: 80
        - path: /add
          backend:
              serviceName: update
              servicePort: 80
        - path: /
          backend:
              serviceName: search-flask
              servicePort: 80