apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: path-based-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
    - hosts:
      -  {{FQDN}}
      secretName: {{SEC_NAME}}
  rules:
    - host: {{FQDN}}
      http:
        paths:
        - path: /choose
          backend:
              serviceName: update
              servicePort: 80
        - path: /update
          backend:
              serviceName: update
              servicePort: 80
        - path: /delete
          backend:
              serviceName: update
              servicePort: 80
        - path: /add
          backend:
              serviceName: update
              servicePort: 80
        - path: /
          backend:
              serviceName: search-flask
              servicePort: 80

